### ISSUE TITLE
Wrong PCI function when reading number of nb p-states

### ISSUE THREAD

**Issue by johkra** [mpollice/AmdMsrTweaker#4]
Hello,

in Info.cpp:69 there's the following line:  eax = ReadPciConfig(AMD_CPU_DEVICE, 0xf5, 0x170);

The 0xf5 should be a 5. The notation in the BKDG is d18f5x170 (device 18, function 5 and register(?) 170) which probably lead to the typo.

**Comment by mpollice** [comment]
I will test this tomorrow, but you seem to be right. It doesn't cause any issues due to the masking in ReadPciConfig, but I will fix it nonetheless for consistency reasons.
