### ISSUE TITLE
NB voltages for AMD A6-3400m 

### ISSUE THREAD

**Issue by ghost** [mpollice/AmdMsrTweaker#5]
Hi. Can you make it so that changing the Northbridge (NB) voltages would work with Llano processors?
I tried it on Windows and they don't change. I peeked at the voltages with FusionTweaker (it's on googlecode) and they weren't changed, however FT can actually change the voltages (but not the frequency and not the multiplier - i guess these are not possible anyway on Llano anyway)

I would look at their code myself but it would take me 2 years to understand all :D 

```
vendor_id   : AuthenticAMD
cpu family  : 18
model       : 1
model name  : AMD A6-3400M APU with Radeon(tm) HD Graphics
stepping    : 0
...
cpu cores   : 4
...
```

If you need any help from my part, I'd be happy to.

I actually looked in AmdMsrTweaker's code and realized that nothing is being done to change the NB voltages (in `Worker::ApplyChanges()` the first `if` and `else if` don't trigger, so I added an `else` there to tell me that nothing's being done to change the NB voltages just so that I don't mistakenly assume they did change - in linux I've no way to check them, only on Windows with FT)

Thanks for your consideration.
Peaces

**Comment by mpollice** [comment]
Hi,
messing with the NB Voltage/Clock on Llano is an elaborate procedure. I once considered to implement it but due to time constraints didn't bother with it anymore. If you look at the source code of FusionTweaker you will see what I mean. But I might look into it the next time I hack around this tool.

However, I wonder what you want to accomplish. Undervolting the NB wont get you much in terms of power savings.

**Comment by ghost** [comment]
I am hoping it would help with temperature decrease but I haven't checked the differences yet. But for me it's a matter of principle, if I am undervolting the CPU and the NB can also be undervolted then I'd prefer to undervolt it, even if there are no noticeable differences in temperatures or power savings.  But you're making me realize that I could compromise and not insist that I need to undervolt the NB voltages also. (though this does make me subconsciously sad)

I was testing these on windows, I can get the NB voltages from:
0.9875V to 0.8750V
and for the second NB P-state:
0.8875V to 0.7500V

( I used to think that they were stable enough at 2 x 0.0125V less than that but nope - I ended up increasing by two steps because they'd rarely BSOD or get messy(then black) screen. )

Just in case, for future reference or what not, I post here what it looks like in FusionTweaker when NB voltages are not changed at all (so, the factory defaults after reboot) but the CPU voltages were changed (by k10stat) so ignore those(they are only relevant for lenovo ideapad Z575 i guess):

![capture_003_03032014_022454](https://f.cloud.github.com/assets/5661825/2306137/65b5aeaa-a27c-11e3-972d-10a202d389fa.jpg)

and fusiontweaker.log file:

```
Family: 12h
Bit numbering   63   59   55   51   47   43   39   35   31   27   23   19   15   11   7    3  0
COFVID 0071     0000 0000 0011 0001 0110 0000 1001 0111 0101 1010 0000 0001 0101 0111 1000 0010 
P-State0 0064   1000 0000 0000 0000 0000 0001 0111 1101 0000 0000 0000 0000 0100 1101 1100 0010 
P-State0 0065   1000 0000 0000 0000 0000 0001 0100 0000 0000 0000 0000 0000 0101 0111 1000 0010 
P-State0 0066   1000 0000 0000 0000 0000 0001 0011 0111 0000 0000 0000 0000 0110 0001 0100 0010 
P-State0 0067   1000 0000 0000 0000 0000 0001 0011 0010 0000 0000 0000 0000 0110 0101 0010 0010 
P-State0 0068   1000 0000 0000 0000 0000 0001 0010 1110 0000 0000 0000 0000 0110 1011 0000 0010 
P-State0 0069   1000 0000 0000 0000 0000 0001 0010 1011 0000 0000 0000 0000 1000 1001 0000 0100 
P-State0 006A   1000 0000 0000 0000 0000 0001 0010 0111 0000 0000 0000 0000 1000 1000 0000 0010 
P-State0 006B   1000 0000 0000 0000 0000 0001 0010 0101 0000 0000 0000 0000 1000 1000 0000 0010 
MainPllOpFreqIdMax: 24 StartupPstate: 7 MinVid(V): 0.45 MaxVid(V): 1.325
 CurPstateLimit: 0 CurPstate: 1 PstateInProgress: 0
 CurCpuVid(V): 1.0125 CurNbVid(V): 0.9875
 CurCpuFid: 24 CurCpuDid: 2
Pstate: P0 PStateEn: 1 IddDiv: 01 IddValue: 125
CpuVid(V): 1.075 CpuFid: 28 CpuDid: 2
Pstate: P1 PStateEn: 1 IddDiv: 01 IddValue: 64
CpuVid(V): 1.0125 CpuFid: 24 CpuDid: 2
Pstate: P2 PStateEn: 1 IddDiv: 01 IddValue: 55
CpuVid(V): 0.95 CpuFid: 20 CpuDid: 2
Pstate: P3 PStateEn: 1 IddDiv: 01 IddValue: 50
CpuVid(V): 0.925 CpuFid: 18 CpuDid: 2
Pstate: P4 PStateEn: 1 IddDiv: 01 IddValue: 46
CpuVid(V): 0.8875 CpuFid: 16 CpuDid: 2
Pstate: P5 PStateEn: 1 IddDiv: 01 IddValue: 43
CpuVid(V): 0.7 CpuFid: 16 CpuDid: 4
Pstate: P6 PStateEn: 1 IddDiv: 01 IddValue: 39
CpuVid(V): 0.7 CpuFid: 0 CpuDid: 2
Pstate: P7 PStateEn: 1 IddDiv: 01 IddValue: 37
CpuVid(V): 0.7 CpuFid: 0 CpuDid: 2
CPB: 1 HwPstate: 1


Bit numbering           31   27   23   19   15   11   7    3  0
NB P-State0 1001 1001 1000 1010 1101 0111 0011 0010 
NB P-State1 1000 0000 0000 0000 0011 0101 0010 1000 
MSRC001_0061 P-StateMaxPState: 6 MinPState: 0
BIOS vendor BIOS version    MoBo vendor MoBo name
LENOVO
54CN18WW
Lenovo
Torpedo
```

and this is when they are changed (to what I said at the top):
![capture_002_03032014_022323](https://f.cloud.github.com/assets/5661825/2306141/9362f93e-a27c-11e3-90b2-dd7264c9e795.jpg)

(i've no .log file for this, currently)

Anyway, I guess I can let it go and just do the cpu undervolting without also NB undervolting.
Peaces

**Comment by mpollice** [comment]
To convince me to put in the effort you could try to quantify the benefit of undervolting the NB. I simply didn't bother since it would involve an elaborate 3-stage process to apply a new NB voltage and also because Llano by now is already superseded. I would also like to improve support for Zacate and Kabini, but I don't have the hardware so I'd have to blindly work on it based on datasheets. The biggest problem is time.

**Comment by ghost** [comment]
To be honest I don't really want to convince you; I'd rather respect your initial choice of not doing it. I would do it myself but I don't have those skills - or at the very least it would take me much more time and I wouldn't be confident that I covered all the cases (even if I were to figure out exactly how FT is doing it and replicate that - but I've to admit, after this, I do feel slightly inspired to look and try to understand its source code)

But I could "try to quantify the benefit of undervolting the NB" regardless. I'll let you know what I find out... 

EDIT: 
ok I've actually tried to see if there are any temperature differences and I've seen none; actually when using the normal NB voltages I've seen a 1 degree drop (from 70 to 69 deg.celsius for APU, 52 to 51 for TZS1 and no change for TZS0 as 69 degC) but that might've been because the room temperature also decreased by max 2 degrees celsius (I'd say) (because of the time that passed between the tests, the second test being the normal NB voltages and was getting dawn outside, like 6 hours were both tests). I see no point in posting the screenshots though.

EDIT2: perhaps the only weird thing is that HWMonitor reported different Powers (lower for when undervolted, though the temp was higher by 1 degC) here are the two screens anyway:

undervolted NB:
![capture_004_05032014_224230](https://f.cloud.github.com/assets/5661825/2376993/52eb183a-a87d-11e3-8463-c5b9a63796f6.jpg)

normal volted NB:
![capture_003_06032014_051723](https://f.cloud.github.com/assets/5661825/2377000/65686dc8-a87d-11e3-8671-137a8f824ded.jpg)

the cpu profile used in k10stat was the same in both cases

**Comment by ghost** [comment]
Ok, I've just confirmed what I said in edit2 above that given the only change is NB voltages the HWMonitor reported Powers are changed, so I'm guessing they are using the NB voltage to compute that, but I don't want to believe that's actually accurate in real world. If it were then it would means that at max CPU usage I'd get 12.35W (68.9-56.55) less by underclocking my NB voltages by 0.1125V at P0 and 0.1375V at P1,  and when CPU is idle I'd get 3.8W less.

I really doubt this is the case. Perhaps I should try draining my battery once, let it charge fully, wait 24 hours after that(to make sure it's charged or something), then unplug power while holding the cpu at 100% usage in P0 and NB in P0 and see how long that lasts until battery empty. Then do it again for normal NB voltages. But I'm kinda reluctant to do this because time and I don't really want to prove that indeed it saves power because I don't think it will show that. 

Anyway, I agree and understand your position: time. 
I think I will go with and accept normal NB voltages as soon as I get rid of Windows and get back to Linux only. 

Thanks.
Peaces.
